name: pinsoftfilm
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #splash_screen
  animated_splash_screen: ^1.3.0

  #internet_connection_control
  connectivity_plus: ^2.3.5

  #lottie
  lottie: ^1.4.3

  #state_managment
  get: ^4.6.5

  #service
  vexana: ^3.0.1

  #google
  json_serializable: ^6.5.3
  json_annotation: ^4.7.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #dart dev
  build_runner: ^2.2.1

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/png/
    - assets/lottie/

  uses-material-design: true

